[["c:/Users/c_nic/anaconda3/Lib/site-packages/service_identity/__init__.py",[false,[["CertificateError",true,2,["CertificateError","c:/Users/c_nic/anaconda3/Lib/site-packages/service_identity/exceptions.py",5]],["SubjectAltNameWarning",true,2,["SubjectAltNameWarning","c:/Users/c_nic/anaconda3/Lib/site-packages/service_identity/exceptions.py",5]],["VerificationError",true,2,["VerificationError","c:/Users/c_nic/anaconda3/Lib/site-packages/service_identity/exceptions.py",5]]]]]]